<!DOCTYPE html>
<head>
  <link rel="stylesheet" type="text/css" href="../css/evil.css" />
</head>
<body>
  <div class="nav-container">
    {{{nav}}}
  </div>
  <div class="content">
    {{{content}}}
  </div>
  <script type="text/javascript" async
          src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML">
  </script>
  <script type="text/javascript" src="../js/evil.js"></script>
</body>
